-- Migration SQL that drops all table
DROP TABLE IF EXISTS Permission_Resource_Mapping CASCADE;
DROP TABLE IF EXISTS Resource CASCADE;
DROP TABLE IF EXISTS Role_Permission_Mapping CASCADE;
DROP TABLE IF EXISTS Permission CASCADE;
DROP TABLE IF EXISTS Role CASCADE;
DROP TABLE IF EXISTS User_Role_Mapping CASCADE;
DROP TABLE IF EXISTS UserProfile CASCADE;